// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeoptpsSqj-y5r4Nc65Hak634ykNd_uMo',
    appId: '1:840253496654:web:f2e04ead1737916556921f',
    messagingSenderId: '840253496654',
    projectId: 'blog-app-231191956',
    authDomain: 'blog-app-231191956.firebaseapp.com',
    storageBucket: 'blog-app-231191956.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKQNK0bGqNNNNKZ5NOAorHzVC7zjFYRyI',
    appId: '1:840253496654:android:776601e30b92347556921f',
    messagingSenderId: '840253496654',
    projectId: 'blog-app-231191956',
    storageBucket: 'blog-app-231191956.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_Ebk0uM_qX0O7lC8Fj4CzFy0-EFbe6wM',
    appId: '1:840253496654:ios:1ee1ca03cec0c64656921f',
    messagingSenderId: '840253496654',
    projectId: 'blog-app-231191956',
    storageBucket: 'blog-app-231191956.appspot.com',
    iosClientId: '840253496654-tk4c9rta28ho68mnukah4a50f7nhfv0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_Ebk0uM_qX0O7lC8Fj4CzFy0-EFbe6wM',
    appId: '1:840253496654:ios:1ee1ca03cec0c64656921f',
    messagingSenderId: '840253496654',
    projectId: 'blog-app-231191956',
    storageBucket: 'blog-app-231191956.appspot.com',
    iosClientId: '840253496654-tk4c9rta28ho68mnukah4a50f7nhfv0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogApp',
  );
}
